package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: base_roles
 */
@Data
public class BaseRoles implements Serializable {
    /**
     * 角色ID
     * Column:    RoleID
     * Nullable:  false
     */
    private Integer roleid;

    /**
     * 角色名
     * Column:    RoleName
     * Nullable:  false
     */
    private String rolename;

    /**
     * 角色描述
     * Column:    Description
     * Nullable:  false
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}