package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: base_classes
 */
@Data
public class BaseClasses implements Serializable {
    /**
     * 分类ID
     * Column:    ClassID
     * Nullable:  false
     */
    private Integer classid;

    /**
     * 父分类
     * Column:    ParentClassID
     * Nullable:  false
     */
    private Integer parentclassid;

    /**
     * 分类名
     * Column:    ClassName
     * Nullable:  false
     */
    private String classname;

    /**
     * 分类图片
     * Column:    ClassImg
     * Nullable:  true
     */
    private String classimg;

    /**
     * 描述
     * Column:    ClassDescription
     * Nullable:  true
     */
    private String classdescription;

    /**
     * 排序
     * Column:    Sort
     * Nullable:  true
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}