package com.retech.qc.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: base_logs
 */
@Data
public class BaseLogs implements Serializable {
    /**
     * 日志ID
     * Column:    LogID
     * Nullable:  false
     */
    private Integer logid;

    /**
     * 日志类型
     * Column:    LogType
     * Nullable:  false
     */
    private Integer logtype;

    /**
     * 日志详细
     * Column:    LogDetail
     * Nullable:  false
     */
    private String logdetail;

    /**
     * 创建者
     * Column:    Creator
     * Nullable:  true
     */
    private Integer creator;

    /**
     * 创建时间
     * Column:    CreateTime
     * Nullable:  false
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}