package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: base_dics
 */
@Data
public class BaseDics implements Serializable {
    /**
     * 字典ID
     * Column:    DicID
     * Nullable:  false
     */
    private Integer dicid;

    /**
     * 字典类型
     * Column:    DicType
     * Nullable:  true
     */
    private String dictype;

    /**
     * 字典名
     * Column:    DicName
     * Nullable:  true
     */
    private String dicname;

    /**
     * 字典值
     * Column:    DicValue
     * Nullable:  true
     */
    private String dicvalue;

    /**
     * 字典类型中文名
     * Column:    DicTypeName
     * Nullable:  true
     */
    private String dictypename;

    /**
     * 是否字典类型
     * Column:    IsDicType
     * Nullable:  true
     */
    private Integer isdictype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}