package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: base_rolemenu
 */
@Data
public class BaseRolemenu implements Serializable {
    /**
     * Column:    ID
     * Nullable:  false
     */
    private Integer id;

    /**
     * 角色ID
     * Column:    RoleID
     * Nullable:  true
     */
    private Integer roleid;

    /**
     * 菜单ID
     * Column:    MenuID
     * Nullable:  true
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}