package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: base_menus
 */
@Data
public class BaseMenus implements Serializable {
    /**
     * 菜单ID
     * Column:    MenuID
     * Nullable:  false
     */
    private Integer menuid;

    /**
     * 菜单名
     * Column:    MenuName
     * Nullable:  false
     */
    private String menuname;

    /**
     * 父菜单
     * Column:    ParentMenuID
     * Nullable:  true
     */
    private Integer parentmenuid;

    /**
     * 路径
     * Column:    Path
     * Nullable:  true
     */
    private String path;

    /**
     * 描述
     * Column:    Description
     * Nullable:  true
     */
    private String description;

    /**
     * 排序
     * Column:    Sort
     * Nullable:  false
     */
    private Integer sort;

    /**
     * Column:    IsOutLink
     * Nullable:  true
     */
    private Integer isoutlink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}