package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: base_mgrole
 */
@Data
public class BaseMgrole implements Serializable {
    /**
     * 用户ID
     * Column:    UserID
     * Nullable:  true
     */
    private Integer userid;

    /**
     * 角色ID
     * Column:    RoleID
     * Nullable:  true
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}