package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: db_datalibrarys
 */
@Data
public class DbDatalibrarys implements Serializable {
    /**
     * 库ID
     * Column:    DataBaseID
     * Nullable:  false
     */
    private Integer databaseid;

    /**
     * 库英文名
     * Column:    DataBaseName
     * Nullable:  false
     */
    private String databasename;

    /**
     * 库中文名
     * Column:    DataBaseCName
     * Nullable:  false
     */
    private String databasecname;

    /**
     * 库描述
     * Column:    Description
     * Nullable:  true
     */
    private String description;

    /**
     * 模型ID
     * Column:    MouldID
     * Nullable:  false
     */
    private Integer mouldid;

    /**
     * 状态
     * Column:    Status
     * Nullable:  false
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_datalibrarys
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}