package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: db_librarynexus
 */
@Data
public class DbLibrarynexus implements Serializable {
    /**
     * Column:    nexusid
     * Nullable:  false
     */
    private Integer nexusid;

    /**
     * Column:    mdbname
     * Nullable:  true
     */
    private String mdbname;

    /**
     * Column:    mdbfield
     * Nullable:  true
     */
    private String mdbfield;

    /**
     * Column:    sdbname
     * Nullable:  true
     */
    private String sdbname;

    /**
     * Column:    sdbnamefield
     * Nullable:  true
     */
    private String sdbnamefield;

    /**
     * Column:    sdbvaluefield
     * Nullable:  true
     */
    private String sdbvaluefield;

    /**
     * Column:    sdbsql
     * Nullable:  true
     */
    private String sdbsql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}