package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: db_moulds
 */
@Data
public class DbMoulds implements Serializable {
    /**
     * 模型ID
     * Column:    MouldID
     * Nullable:  false
     */
    private Integer mouldid;

    /**
     * 模型名称
     * Column:    MouldName
     * Nullable:  false
     */
    private String mouldname;

    /**
     * 模型描述
     * Column:    Description
     * Nullable:  true
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}