package com.retech.qc.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * Table: nation
 */
@Data
public class Nation implements Serializable {
    /**
     * 主键
     * Column:    NationID
     * Nullable:  false
     */
    private Integer nationid;

    /**
     * 名族名
     * Column:    NationName
     * Nullable:  false
     */
    private String nationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    private static final long serialVersionUID = 1L;
}