package com.retech.qc.mapper;

import com.retech.qc.entity.BaseMenus;
import com.retech.qc.entity.BaseMenusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseMenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseMenus> selectByExampleWithRowbounds(BaseMenusExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseMenus> selectByExample(BaseMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseMenus selectByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseMenus record, @Param("example") BaseMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseMenus record, @Param("example") BaseMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseMenus record);
}