package com.retech.qc.mapper;

import com.retech.qc.entity.BaseRolemenu;
import com.retech.qc.entity.BaseRolemenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseRolemenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseRolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseRolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseRolemenu> selectByExampleWithRowbounds(BaseRolemenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseRolemenu> selectByExample(BaseRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseRolemenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseRolemenu record, @Param("example") BaseRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseRolemenu record, @Param("example") BaseRolemenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseRolemenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_rolemenu
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseRolemenu record);
}