package com.retech.qc.mapper;

import com.retech.qc.entity.BaseMgrole;
import com.retech.qc.entity.BaseMgroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseMgroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseMgroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseMgroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseMgrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseMgrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseMgrole> selectByExampleWithRowbounds(BaseMgroleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseMgrole> selectByExample(BaseMgroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseMgrole record, @Param("example") BaseMgroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_mgrole
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseMgrole record, @Param("example") BaseMgroleExample example);
}