package com.retech.qc.mapper;

import com.retech.qc.entity.BaseManagers;
import com.retech.qc.entity.BaseManagersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseManagersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseManagersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseManagersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseManagers> selectByExampleWithRowbounds(BaseManagersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseManagers> selectByExample(BaseManagersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseManagers selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseManagers record, @Param("example") BaseManagersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseManagers record, @Param("example") BaseManagersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseManagers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_managers
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseManagers record);
}