package com.retech.qc.mapper;

import com.retech.qc.entity.BaseClasses;
import com.retech.qc.entity.BaseClassesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer classid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseClasses> selectByExampleWithRowbounds(BaseClassesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseClasses> selectByExample(BaseClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseClasses selectByPrimaryKey(Integer classid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseClasses record, @Param("example") BaseClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseClasses record, @Param("example") BaseClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseClasses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_classes
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseClasses record);
}