package com.retech.qc.mapper;

import com.retech.qc.entity.BaseDics;
import com.retech.qc.entity.BaseDicsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseDicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseDicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseDicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer dicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseDics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseDics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseDics> selectByExampleWithRowbounds(BaseDicsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseDics> selectByExample(BaseDicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseDics selectByPrimaryKey(Integer dicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseDics record, @Param("example") BaseDicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseDics record, @Param("example") BaseDicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseDics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dics
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseDics record);
}