package com.retech.qc.mapper;

import com.retech.qc.entity.BaseLogs;
import com.retech.qc.entity.BaseLogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseLogs> selectByExampleWithRowbounds(BaseLogsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseLogs> selectByExample(BaseLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseLogs selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseLogs record, @Param("example") BaseLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseLogs record, @Param("example") BaseLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_logs
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseLogs record);
}