package com.retech.qc.mapper;

import com.retech.qc.entity.BaseRoles;
import com.retech.qc.entity.BaseRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BaseRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(BaseRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(BaseRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseRoles> selectByExampleWithRowbounds(BaseRolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<BaseRoles> selectByExample(BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    BaseRoles selectByPrimaryKey(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseRoles record, @Param("example") BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") BaseRoles record, @Param("example") BaseRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(BaseRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_roles
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(BaseRoles record);
}