package com.retech.qc.mapper;

import com.retech.qc.entity.DbLibrarynexus;
import com.retech.qc.entity.DbLibrarynexusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DbLibrarynexusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(DbLibrarynexusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(DbLibrarynexusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer nexusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(DbLibrarynexus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(DbLibrarynexus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<DbLibrarynexus> selectByExampleWithRowbounds(DbLibrarynexusExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<DbLibrarynexus> selectByExample(DbLibrarynexusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    DbLibrarynexus selectByPrimaryKey(Integer nexusid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") DbLibrarynexus record, @Param("example") DbLibrarynexusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") DbLibrarynexus record, @Param("example") DbLibrarynexusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(DbLibrarynexus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_librarynexus
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(DbLibrarynexus record);
}