package com.retech.qc.mapper;

import com.retech.qc.entity.DbMetadatas;
import com.retech.qc.entity.DbMetadatasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DbMetadatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(DbMetadatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(DbMetadatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer metadataid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(DbMetadatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(DbMetadatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<DbMetadatas> selectByExampleWithRowbounds(DbMetadatasExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<DbMetadatas> selectByExample(DbMetadatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    DbMetadatas selectByPrimaryKey(Integer metadataid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") DbMetadatas record, @Param("example") DbMetadatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") DbMetadatas record, @Param("example") DbMetadatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(DbMetadatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_metadatas
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(DbMetadatas record);
}