package com.retech.qc.mapper;

import com.retech.qc.entity.DbMoulds;
import com.retech.qc.entity.DbMouldsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DbMouldsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(DbMouldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(DbMouldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer mouldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(DbMoulds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(DbMoulds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<DbMoulds> selectByExampleWithRowbounds(DbMouldsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<DbMoulds> selectByExample(DbMouldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    DbMoulds selectByPrimaryKey(Integer mouldid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") DbMoulds record, @Param("example") DbMouldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") DbMoulds record, @Param("example") DbMouldsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(DbMoulds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_moulds
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(DbMoulds record);
}