package com.retech.qc.mapper;

import com.retech.qc.entity.FrontUserinfo;
import com.retech.qc.entity.FrontUserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FrontUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(FrontUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(FrontUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontUserinfo> selectByExampleWithBLOBsWithRowbounds(FrontUserinfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontUserinfo> selectByExampleWithBLOBs(FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontUserinfo> selectByExampleWithRowbounds(FrontUserinfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontUserinfo> selectByExample(FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    FrontUserinfo selectByPrimaryKey(Integer seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") FrontUserinfo record, @Param("example") FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") FrontUserinfo record, @Param("example") FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") FrontUserinfo record, @Param("example") FrontUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(FrontUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(FrontUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_userinfo
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(FrontUserinfo record);
}