package com.retech.qc.mapper;

import com.retech.qc.entity.FrontProduct;
import com.retech.qc.entity.FrontProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FrontProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(FrontProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(FrontProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontProduct> selectByExampleWithBLOBsWithRowbounds(FrontProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontProduct> selectByExampleWithBLOBs(FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontProduct> selectByExampleWithRowbounds(FrontProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<FrontProduct> selectByExample(FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    FrontProduct selectByPrimaryKey(Integer seqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") FrontProduct record, @Param("example") FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") FrontProduct record, @Param("example") FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") FrontProduct record, @Param("example") FrontProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(FrontProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(FrontProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table front_product
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(FrontProduct record);
}