package com.retech.qc.mapper;

import com.retech.qc.entity.Nation;
import com.retech.qc.entity.NationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int countByExample(NationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByExample(NationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int deleteByPrimaryKey(Integer nationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insert(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int insertSelective(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<Nation> selectByExampleWithRowbounds(NationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    List<Nation> selectByExample(NationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    Nation selectByPrimaryKey(Integer nationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") Nation record, @Param("example") NationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByExample(@Param("record") Nation record, @Param("example") NationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKeySelective(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Wed Jan 16 10:54:37 CST 2019
     */
    int updateByPrimaryKey(Nation record);
}